### ISSUE TITLE
T35 Display, has pixel shift on x axis when drawing edge to edge, Expose ScreenWidth & Height properties

### ISSUE THREAD

**Issue by PRIMETSS** [Gravicode/GadgeteerToTinyCLR#6]
Found that when drawing to screen there was some pixel shifting on the display, so had to introduce offsets. Traced the issue to timing issue with HorizontalBackPorch = 27.
Using HorizontalBackPorch = 29;  seems to have fixed it and can now draw edge to edge on display.
Also propose exposing ScreenHeight & ScreenWideth as properties on the T35 class to expose the displays Width & Height.
I'll submit a pull request to review if thats ok?

`this.Screen.DrawLine(new System.Drawing.Pen(Color.Yellow), 2, 0, 2, 234);
`  

`Calc Offsets
this.Screen.DrawLine(new System.Drawing.Pen(Color.Purple), 0, 0, 319, 0);
this.Screen.DrawLine(new System.Drawing.Pen(Color.Yellow), 0, 0, 0, 234);
this.Screen.DrawLine(new System.Drawing.Pen(Color.Red), 0, 234, 319, 234);
this.Screen.DrawLine(new System.Drawing.Pen(Color.Gray), 319, 0, 319, 234);
`

**Comment by mifmasterz** [comment]
ok
